name: '배포 알리미'
description: '스매치 서비스들 배포 알림을 위한 액션입니다.'
author: smatch-corp/w00ing

branding:
  icon: 'bell'
  color: 'blue'

inputs:
  team:
    description: '팀명 (ex. Front-End, Back-End, Core)'
    required: true
    default: 테스트 팀
  service-name:
    description: '서비스명 (ex. 스매치, 스매치어드민, 패스트매치)'
    required: true
    default: 테스트 서비스
  environment:
    description: '배포 환경 (test, stage, prod)'
    required: true
    default: 테스트 환경
  channel-id:
    description: '배포 알림 채널 ID'
    required: true
    default: 'C06H62PLQNN'
  phase:
    description: '액션 타입 (start, finish)'
    required: true
    default: finis

outputs:
  time:
    description: 'Your output description here'

runs:
  using: 'node20'
  main: 'dist/index.js'
