name: '배포 알리미'
description: '스매치 서비스들 배포 알림을 위한 액션입니다.'
author: smatch-corp/w00ing

branding:
  icon: 'bell'
  color: 'blue'

inputs:
  team:
    description: '팀명 (ex. Front-End, Back-End, Core)'
    required: true
  service_name:
    description: '서비스명 (ex. 스매치, 스매치어드민, 패스트매치)'
    required: true
  environment:
    description: '배포 환경 (test, stage, prod)'
    required: true
  channel_id:
    description: '배포 알림 채널 ID'
    required: true
  member_id:
    description: '멘션할 슬랙 멤버 ID'
    required: true
  phase:
    description: '액션 타입 (start, finish)'
    required: true

outputs:
  thread_ts:
    description: Thread timestamp ('start' phase에서만 출력)

runs:
  using: 'node20'
  main: 'dist/index.js'
