name: Continuous Integration

on:
  push:
    branches:
      - main
      - test
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Check Format
        id: pnpm-format-check
        run: pnpm run format:check

      - name: Lint
        id: pnpm-lint
        run: pnpm run lint

      - name: Test
        id: pnpm-ci-test
        run: pnpm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
        env:
          BEFORE_REF: ${{ github.event.before }}

      - name: Test Start Action
        id: test-start-action
        uses: ./
        with:
          channel_id: 'C06H62PLQNN'
          # group_id: 'S03V01C0H61'
          group_id: 'U02U5KJ3G7P'
          phase: 'start'
          team: Front-End
          service_name: 스매치어드민
          environment: dev
          before_ref: ${{ env.BEFORE_REF }}
        env:
          SLACKBOT_TOKEN: ${{ secrets.DISTRIBUTION_SLACKBOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print Start Action Output
        id: thread_ts
        run: echo "${{ steps.test-start-action.outputs.thread_ts }}"

      - name: Sleep for 10 seconds
        run: sleep 10s
        shell: bash

      - name: Test Finish Action
        id: test-finish-action
        uses: ./
        with:
          channel_id: 'C06H62PLQNN'
          # group_id: 'S03V01C0H61'
          group_id: 'U02U5KJ3G7P'
          phase: 'finish'
          team: Front-End
          service_name: 스매치어드민
          environment: dev
          before_ref: ${{ env.BEFORE_REF }}
          thread_ts: ${{ steps.test-start-action.outputs.thread_ts }}
        env:
          SLACKBOT_TOKEN: ${{ secrets.DISTRIBUTION_SLACKBOT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
